on: workflow_dispatch
name: main
jobs:
  build:
    name: install dependencies
    runs-on: ubuntu-latest
    steps:
    - name: Set up Flutter
      uses: subosito/flutter-action@v1
      with:
        flutter-version: '2.5.3' # Specify the version of Flutter you want to use

    - name: Install dependencies
      run: flutter pub get
      working-directory: ./
    - name: Run tests
      run: flutter test

    - name: Build APK
      run: flutter build apk --release
