on: workflow_dispatch
name: main
jobs:
  build:
    name: install dependencies
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@master
      
    - name: Print current directory
      run: echo "Current directory is ${{ github.workspace }}"
      
    - name: clean stale build and cache
      uses: jddeep/Flutter-Runner@1.2.0
      with:
        args: clean

    - name: install dependencies
      uses: jddeep/Flutter-Runner@1.2.0
      with:
        args: pub get

    - name: build apk
      uses: jddeep/Flutter-Runner@1.2.0
      with:
        args: build apk --release
